name: build

on: 
  pull_request:
  push:
    branches: 
      - master

env:
  BUILD_TYPE: Release

jobs:  
  ubuntu-22-04:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@master
    - name: install pre-reqs and build
      run: sudo ./install/installUbuntu.sh
    - name: test
      run: |
        ./build/usher --help
        ./build/matUtils --help
        mpirun -np 1 ./build/matOptimize --help
        ./build/ripples --help
        command -v mafft

